
BINARY = main

OBJS = HAL.o kiss_fft.o mini-printf.o

OPENCM3_DIR = ../libopencm3

#DEVICE=STM32F407VG
LDSCRIPT = $(OPENCM3_DIR)/lib/stm32/f4/stm32f4-discovery.ld
#LDSCRIPT = $(OPENCM3_DIR)/lib/libopencm3_stm32f4.ld
#LDSCRIPT = $(OPENCM3_DIR)/lib/stm32/f4/stm32f405x6.ld

include libopencm3.target.mk